Repository jainaman224/Algo_Ds_Notes, pull requests merged in 2020-04, with the labels that each got.

#2585 Create Tree_Preorder_Traversal.kt
  Tree_Preorder_Traversal/Tree_Preorder_Traversal.kt
Labels: GSSoC20, easy

#2543 Aggressive cows
  Aggressive_Cows/Aggressive_Cows.java
Labels: GSSoC20, easy

#2636 Logistic Regression in Python
  Machine_Learning/Logistic_Regression/Logistic_Regression.ipynb
Labels: GSSoC20, medium

#2567 Johnson Algorithm Implementation in Dart
  Johnson_Algorithm/Johnson_Algorithm.dart
Labels: GSSoC20, medium

#2604 Boyer Moore Algorithm in C#
  Boyer_Moore_Algorithm/Boyer_Moore.cs
Labels: GSSoC20, easy

#2685 Adding PHP Implementation for Chinese Remainder Theorem (Issue #2481)
  Chinese_Remainder_Theorem/Chinese_Remainder_Theorem.php
Labels: GSSoC20, easy

#1845 Added Minimum Absolute Difference in Array problem [C and C++ implementation]
  Minimum_Absolute_Difference_In_Array/Minimum_Absolute_Difference_In_Array.c
  Minimum_Absolute_Difference_In_Array/Minimum_Absolute_Difference_In_Array.cpp
Labels: GSSoC20, easy

#2605 Quick Sort 3 way in Ruby
  Quicksort_3_way/quick_sort_3_way.rb
Labels: GSSoC20, easy

#2617 Dijkstra Algorithm implementation in dart
  Dijkstra_Algorithm/Dijkstra_Algorithm.dart
Labels: GSSoC20, medium

#2693 added selection sort logic in typescript
  Selection_Sort/Selection_Sort.ts
Labels: GSSoC20, easy

#2534 Kadane Algorithm
  Kadane_Algorithm/Kadane_Algorithm.go
Labels: GSSoC20, easy

#2644 Boyer Moore Algo in c
  Boyer_Moore_Algorithm/Boyer_Moore.c
Labels: GSSoC20, easy

#2687 Boyer Moore in Go
  Boyer_Moore_Algorithm/Boyer_Moore.go
Labels: GSSoC20, easy

#2255 Kruskal Algorithm in C
  Kruskal_Algorithm/Kruskal_Algorithm.c
Labels: GSSoC20, medium

#2635 Breadth First Search in Ruby
  Breadth_First_Search/Breadth_First_Search.rb
Labels: GSSoC20, easy

#2583 Backtracking
  Backtracking_using_bitmask/Backtrack_using_bitmask.cpp
  Backtracking_using_bitmask/Backtrack_using_bitmask.java
  Backtracking_using_bitmask/Backtrack_using_bitmask.py
Labels: GSSoC20, medium

#2529 Transpose of matrix in java
  Matrix_Operations/Java/Matrix_transpose.java
Labels: GSSoC20, easy

#2682 Kruskal Algorithm Implementation in python
  Kruskal_Algorithm/Kruskal_Algorithm.py
Labels: GSSoC20, medium

#2720 Tree Preorder Traversal in Dart
  Tree_Preorder_Traversal/Tree_Preorder_Traversal.dart
Labels: GSSoC20, easy

#2676 Segment Tree Range Minimum Query in C
  Segment_Tree_RMQ/Segement_Tree_RMQ.c
Labels: GSSoC20, medium

#2674 Depth First Search in C#
  Depth_First_Search/Depth_First_Search.cs
Labels: GSSoC20, easy

#2598 Added code of Longest Increasing Subsequence in Java
  Longest_Increasing_Subsequence/LIS.java
Labels: GSSoC20, easy

#2679 AVL Tree implementation in C++
  AVL_Tree/AVL_Tree.cpp
Labels: GSSoC20, medium

#2669 Adding PHP implementation for LIS (Issue #2253)
  Longest_Increasing_Subsequence/LIS.php
Labels: GSSoC20, easy

#2684 Prims Algorithm in C#
  Prims_Algorithm/Prims_Algorithm.cs
Labels: GSSoC20, medium

#2642 Tree- level order traversal in JS
  Tree_Levelorder_Traversal/Tree_Levelorder_Traversal.js
Labels: GSSoC20, easy

#2514 Breadth First Search in Csharp #2171
  Breadth_First_Search/BFS_in_Csharp.cs
Labels: GSSoC20, easy

#2763 Chinese remainder theorem dart
  Chinese_Remainder_Theorem/Chinese_Remainder_Theorem.dart
Labels: GSSoC20, beginner

#2334 Johnson Algorithm implementation in C (Issue #2206)
  Johnson_Algorithm/Johnson_Algorithm.c
Labels: GSSoC20, medium

#2757 Add Level Order Traversal in Kotlin
  Tree_Levelorder_Traversal/Tree_Levelorder_Traversal.kt
Labels: GSSoC20, easy

#2322 Add spiral array in C
  Spiral_Array/SpiralArray.c
Labels: GSSoC20, easy

#2766 Added LCS implementation in Ruby (#2252)
  Longest_Common_Subsequence/Longest_Common_Subsequence.rb
Labels: GSSoC20, easy

#2760 Merge Sort in Rust
  Merge_Sort/Merge_Sort.rs
Labels: GSSoC20, easy

#2745 Created Ternary_Search.kt
  Ternary_Search/Ternary_Search.kt
Labels: GSSoC20, beginner

#2759 Bucket Sort in Ruby
  Bucket_Sort/Bucket_Sort.rb
Labels: GSSoC20, easy

#2799 Segment Tree RMQ implemented in Dart
  Segment_Tree_RMQ/Segment_Tree_RMQ.dart
Labels: GSSoC20, medium

#2832 Added Chinese remainder theorem in C.
  Chinese_Remainder_Theorem/Chinese_remainder_theorem.c
Labels: GSSoC20, beginner
