Repository jainaman224/Algo_Ds_Notes, pull requests merged in 2020-03, with the labels that each got.

#1844 add Armstrong Number code in Golang
  Armstrong_Number/ArmstrongNumber.go
Labels: GSSoC 20, easy

#1753 added boyer moore algo in java
  Boyer_Moore_Algorithm/Boyer_Moore.java
Labels: GSSoC 20, medium

#1754 #1641 GSSoC'20 jump search in c++
  Jump Search/jump_search.cpp
Labels: GSSoC 20, easy

#2137 Create Quick_Sort.cs
  Quick_Sort/Quick_Sort.cs
Labels: GSSoC 20, easy

#1937 BFS for Disconnected Graph in Java
  BFS_Disconnected_Graph/BFS_DisconnectedGraph.java
Labels: GSSoC 20, easy

#1743 Start of loop in a linked list
  Linked_List/StartOfLoop.java
Labels: GSSoC 20, medium

#2119 Create Stooge_Sort.cpp
  Stooge_Sort/Stooge_Sort.cpp
Labels: GSSoC 20, easy

#2169 ADDED Readme for Activity Selection
  Activity_Selection/README.md
Labels: GSSoC 20, easy

#2180 Added JS Implementation for Set_Bits_Till_N
  Set_Bits_Till_N/Set_Bits_Till_N.js
Labels: GSSoC 20, easy

#1944 Implementation of Dijkstra Algorithm in JS
  Dijkstra_Algorithm/Dijkstra_Algorithm.js
Labels: GSSoC 20, medium

#1834 Linear regression using straight line@abhishekgupta368
  Linear_Regression_Using_Straight_Line/Linear_Regression_using_Straight_Line.py
Labels: GSSoC 20, easy

#1847 Cycle sort in JS. Closes #1699
  Cycle_Sort/Cycle_Sort.js
Labels: GSSoC 20, easy

#1833 Doubly Linked List in Java
  Doubly_Linked_List/Doubly_Linked_List.java
Labels: GSSoC 20, easy

#2220 Bucket Sort in Kotlin
  Bucket_Sort/Bucket_Sort.kt
Labels: GSSoC 20, easy

#1832 Depth first search in JS. Closes #1695
  Depth_First_Search/Depth_First_Search.js
Labels: GSSoC 20, easy

#1978 Added Tree_Postorder_Traversal implementation in JavaScript.
  Tree_Postorder_Traversal/Tree_Postorder_Traversal.js
Labels: GSSoC 20, easy

#2264 issue 2024 Fermat_Little_Theorem java
  Fermat_Little_Theorem/Fermat_Little_Theorem.java
Labels: GSSoC 20, easy

#2277 updated Array_Rotation.cpp
  Array_Rotation/Array_Rotation.cpp
Labels: GSSoC 20, easy

#2270 #2151 Added Pancake Sorting in Python
  Pancake_Sort/Pancake_Sort.py
Labels: GSSoC 20, easy

#2294 Solution for #1967
  Gcd/gcd.js
Labels: GSSoC 20, easy

#2183 Rat In Maze
  Rat_in_maze/Rat_in_maze.cpp
Labels: GSSoC 20, medium

#1980 Implementation of Binary Insertion Sort in Python
  Binary_Insertion_Sort/Binary_Insertion_Sort.py
Labels: GSSoC 20, easy

#1748 FIXES #1557 [Added README File]
  Machine_Learning/Linear_Regression/README.md
Labels: GSSoC 20, easy

#1891 A star search@abhishekgupta368
  A_Star_Search_Algorithm/A_Star_Search_Algorithm.py
Labels: GSSoC 20, medium

#1984 Bitwise addition in C and C++ #1838 (GSSoC'20)
  Bitwise_Addition/bitwise_addition.c
  Bitwise_Addition/bitwise_addition.cpp
Labels: GSSoC 20, beginner

#2306 added matrix chain multiplication for python
  Matrix_Chain_Multiplication/Matrix_Chain_Multiplication.py
Labels: GSSoC 20, easy

#2134 Added ReadMe for AKS Primality Test
  AKS_Primarility_Test/README.md
Labels: GSSoC 20, easy

#2197 Code to check whether a LinkedList contains Palindromic data or not
  Check_Palindrome_for_LinkedList/Palindrome.cpp
Labels: GSSoC 20, beginner

#1999 Sort Array of 0's 1's 2's in C++
  Sort_Array_zero_one_two/Sort_Array_zero_one_two.cpp
Labels: GSSoC 20, easy

#2038 Added Digit_Count.rb
  Digit_Count/Digit_Count.rb
Labels: GSSoC 20, easy

#1719 QuickSort Implementation updated to ES6+ syntax in JS
  Quick_Sort/Quick_Sort.js
Labels: GSSoC 20, beginner

#2314 Added Hamiltonian_Cycle.cpp
  Hamiltonian_Cycle/Hamiltonian_Cycle.cpp
Labels: GSSoC 20, medium

#2017 Subsequence of string using bitmasking
  Subsequence_Bitmasking/subsequence_bitmasking.cpp
Labels: GSSoC 20, easy

#2293 Finding last digit of nth fibonacci number
  Last_Digit_of_Nth_Fibonacci_Number/Last_Digit_of_Nth_Fibonacci_Number.cpp
Labels: GSSoC 20, easy

#2379 Added C++ implementation of Regula Falsi method
  Regula_Falsi_Method/regula_falsi.cpp
Labels: GSSoC 20, easy

#1989 Karatsuba Multiplication Algorithm in java #1684 (GSSoC'20)
  Karatsuba_Algo/Karatsuba_multiplication_algo.java
Labels: GSSoC 20, easy

#2069 Quicksortreadme
  Quick_Sort/README.md
Labels: GSSoC 20, easy

#2335 Anagram Program modified .
  Anagram/Anagram.cpp
Labels: GSSoC 20, easy

#1811 infix-to-postfix
  Infix_To_Postfix/Infix_to_Postfix.py
  nCr mod P/nCr_mod_P.cpp
Labels: GSSoC 20, easy

#2234 Spiral Array C++
  Spiral_Array/Spiral_Array.cpp
Labels: GSSoC 20, easy

#1854 Factorial
  Factorial/Factorial.c
  Factorial/Factorial.cpp
  Factorial/Factorial.java
Labels: GSSoC 20, medium

#1902 Minimum inversion cpp code added
  Minimum_inversions/Minimum_inversions.cpp
Labels: GSSoC 20, easy

#2303 EvenOdd Python
  1-D_Array/Python/EvenOdd.py
Labels: GSSoC 20, beginner

#2490 Karatsuba algorithm
  Karatsuba_Algorithm/Karatsuba_multiplication_algo.cpp
  Karatsuba_Algorithm/Readme.md
  Karatsuba_Algorithm/karatsuba.py
Labels: GSSoC20, medium

#2290 Adding ASCII_Subsequence in C, Python and JavaScript (Closes issue #1703)
  Ascii_Subsequences/ASCII_Subsequences.c
  Ascii_Subsequences/ASCII_Subsequences.js
  Ascii_Subsequences/ASCII_Subsequences.py
Labels: GSSoC20, medium

#2402 check whether a string is palindrome
  Palindrome/palindrome_string.py
Labels: GSSoC20, easy

#2362 added Power_Of_Two in JS
  Power_Of_Two/Power_Of_Two.js
Labels: GSSoC20, easy

#2260 Implementation of Pascal Triangle in Java and Python Added (Fixes issue #1818)
  Pascal_Triangle/Pascal_Triangle.java
  Pascal_Triangle/Pascal_Triangle.py
Labels: GSSoC20, easy

#2022 Pancake Sorting in Java
  Pancake_Sort/Pancake_Sort.java
Labels: GSSoC20, easy

#2431 Implementation of Bucket Sort in JS
  Bucket_Sort/Bucket_Sort.js
Labels: GSSoC20, easy

#2383 Create Readme.md
  Ternary_Search/Readme.md
Labels: GSSoC20, beginner

#2074 Added KNN algorithm using C
  Machine_Learning/K_Nearest_Neighbours/K_Nearest_Neighbours.c
Labels: GSSoC20, medium

#2458 Added Bisection_Method.cpp
  Bisection_Method/Bisection_Method.cpp
Labels: GSSoC20, easy

#2471 Circular Queue in JAVA
  Circular_Queue/Circular_Queue.java
Labels: GSSoC20, easy

#2060 Fibonacci_Number using DP approach added
  Fibonacci_Number_Using_DP_Approach/Fibonacci_Number_Using_DP_Approach.c
  Fibonacci_Number_Using_DP_Approach/Fibonacci_Number_Using_DP_Approach.cpp
  Fibonacci_Number_Using_DP_Approach/Fibonacci_Number_Using_DP_Approach.java
Labels: GSSoC20, medium

#2267 Length of Linked List in C, Java Added
  Linked_List/Length_of_Linked_List.c
  Linked_List/Length_of_Linked_List.java
Labels: GSSoC20, beginner

#2420 Implementation of Karatsuba Algorithm in JS
  Karatsuba_Algorithm/Karatsuba_Algorithm.js
Labels: GSSoC20, medium

#2285 Finding last digit of nth term in squares of fibonacci number
  Last_Digit_of_Square_of_Nth_Fibonacci_Number/Last_Digit_of_Square_of_Nth_Fibonacci_Number.cpp
Labels: GSSoC20, easy

#2541 Added minesweeper implementation in C++
  Minesweeper/minesweeper.cpp
Labels: GSSoC20, hard

#1952 LCM of N elements of an array Issue No. #1821
  Largest_Common_Multiple/Largest_Common_Multiple_1-DArray.c
  Largest_Common_Multiple/Largest_Common_Multiple_1-DArray.cpp
  Largest_Common_Multiple/Largest_Common_Multiple_1-DArray.java
Labels: GSSoC20, easy

#1560 Postfix Evaluation in C
  Postfix_Evaluation/Postfix _Evaluation.c
Labels: GSSoC20, easy

#2354 Max_circular_sum_added 2-C/C++
  Max_Circular_SubArray_Sum/max_circular_subArray_sum.c
  Max_Circular_SubArray_Sum/max_circular_subarray_sum.cpp
Labels: GSSoC20, easy

#2230 Implementing ArrayList in Java
  Collections/arrayList.java
Labels: GSSoC20, easy

#2356 Palindromic_string_added 2 C/C++
  palindromic_string/palindromic_string.c
  palindromic_string/palindromic_string.cpp
Labels: GSSoC20, beginner

#2492 check palindrome in a number in Java
  Palindrome/palindrome_no.java
Labels: GSSoC20, easy

#2491 check palindrome in a string in Java
  Palindrome/palindrome_string.java
Labels: GSSoC20, easy

#1804 Rotations in sorted array
  Count_Rotations/Count_Rotations.java
Labels: GSSoC20, easy

#2216 Integer to Roman in C++
  Integer_to_Roman/Integer_to_Roman.cpp
Labels: GSSoC20

#2215 Add Armstrong Number In C# Fixes #1954
  Armstrong_Number/Armstrong_Number.cs
Labels: GSSoC20, easy

#2527 Addition of matrix in java
  Matrix_Operations/Java/Matrix_Addition.java
Labels: GSSoC20, easy

#2643 Priority_Queue.py
  Priority_Queue/Priority_Queue.py
Labels: GSSoC20, easy

#2607 Added implementation of Z-Algorithm in JS
  Z_Algorithm/Z_Algorithm.js
Labels: GSSoC20, easy
