Repository jainaman224/Algo_Ds_Notes, pull requests merged in 2020-05, with the labels that each got.

#2005 Gray Code of input length
  Gray_Code/Gray_Code.cpp
Labels: GSSoC20, easy

#2817 Karatsuba Algorithm In GO
  Karatsuba_Algorithm/Karatsuba_Algorithm.go
Labels: GSSoC20, medium

#2410 Linear Search in dart language
  Linear_Search/Linear_Search.dart
Labels: GSSoC20, easy

#2818 Depth First Search in Go
  Depth_First_Search/Depth_First_Search.go
Labels: GSSoC20, easy

#2831 Quick Sort Implementation in Kotlin
  Quick_Sort/Quick_Sort.kt
Labels: GSSoC20, easy

#2729 Added Postman Sort in JavaScript
  Postman_Sort/Postman_Sort.js
Labels: GSSoC20, easy

#2750 Matrix_identical in java
  Matrix_Operations/Java/Matrix_identical.java
Labels: GSSoC20, easy

#2411 Binary search in dart language
  Binary_Search/Binary_Search.dart
Labels: GSSoC20, easy

#2801 KMP in JavaScript was added
  Knuth_Morris_Pratt_Algorithm/KMP.js
Labels: GSSoC20, easy

#2862 Updated Decimal_to_Binary.cpp
  Number_Conversion/C++/Decimal_to_Binary.cpp
Labels: GSSoC20, beginner

#2815 #2252 - Added LCS in php
  Longest_Common_Subsequence/Longest_Common_Subsequence.php
Labels: GSSoC20, easy

#2772 Created Shell_Sort.php
  Shell_Sort/Shell_Sort.php
Labels: GSSoC20, easy

#2568 adding c file of fenwick tree
  Fenwick_Tree/Fenwick_Tree.c
Labels: GSSoC20, medium

#2528 Subtraction of matrix in java
  Matrix_Operations/Java/Matrix_Subtraction.java
Labels: GSSoC20, easy

#2852 KMP algorithm in dart added
  Knuth_Morris_Pratt_Algorithm/KMP.dart
Labels: GSSoC20, easy

#2272 Added Selection_Sort.php
  Selection_Sort/Selection_Sort.php
Labels: GSSoC20, easy

#2877 Matrix_intersection in java
  Matrix_Operations/Java/Matrix_intersection.java
Labels: GSSoC20, easy

#2843 Readme.md for Chinese_Remainder_Theorem
  Chinese_Remainder_Theorem/Readme.md
Labels: GSSoC20, beginner

#2841 Readme for Segment_Tree_RMQ
  Segment_Tree_RMQ/README.md
Labels: GSSoC20, medium

#2677 Z Algorithm in Rust
  Z_Algorithm/Z_Algorithm.rs
Labels: GSSoC20, easy

#2884 Go Implementation of Heapsort
  Heap_Sort/heapsort.go
Labels: GSSoC20, easy

#2814 Added Knuth Morris Pratt Algorithm in Kotlin
  Knuth_Morris_Pratt_Algorithm/KMP.kt
Labels: GSSoC20, easy

#2848 Added KMP implementation in Ruby (#2555)
  Knuth_Morris_Pratt_Algorithm/KMP.rb
Labels: GSSoC20, easy

#2876 Added DFS in PHP
  Depth_First_Search/Depth_First_Search.php
Labels: GSSoC20, easy

#2895 Intro Sort implementation in Python
  Intro_Sort/introsort.py
Labels: GSSoC20, easy

#2844 Rabin Karp in C
  Rabin_Karp/Rabin_Karp.c
Labels: GSSoC20, easy

#2920 Kosaraju readme added
  Kosaraju_Algorithm/Kosaraju_algorithm.cpp
  Kosaraju_Algorithm/readme.md
Labels: GSSoC20, medium

#2822 sleep sort README.md file
  Sleep_Sort/README.md
Labels: GSSoC20, easy

#2898 Bucket Sort in Go
  Bucket_Sort/Bucket_Sort.go
Labels: GSSoC20, easy

#2914 AVL Tree implemented in Dart
  AVL_Tree/AVL_Tree.dart
Labels: GSSoC20, medium

#2928 Create Pancake_Sort.go
  Pancake_Sort/Pancake_Sort.go
Labels: GSSoC20, easy

#2902 Add Counting Sort in Kotlin
  Counting_Sort/Counting_Sort.kt
Labels: GSSoC20, easy

#2916 Selection sort in rust
  Selection_Sort/Selection_sort.rs
Labels: GSSoC20, easy

#2890 Adding PHP Implementation of Dijkstra's Algo. (Issue #2204)
  Dijkstra_Algorithm/Dijkstra_Algorithm.php
Labels: GSSoC20, medium

#2945 Tree_Inorder_Traversal in TypeScript
  Tree_Inorder_Traversal/Tree_Inorder_Traversal.ts
Labels: GSSoC20, easy

#2865 Added Ford Fulkerson Method in Javascript
  Ford_Fulkerson_Method/Ford_Fulkerson_Method.js
Labels: GSSoC20, easy

#2953 Added extended euclidean algorithm in java
  Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.java
Labels: GSSoC20, beginner

#2957 Added Exponential Search in PHP
  Exponential_Search/Exponential_Search.php
Labels: GSSoC20, easy

#2962 Add Aho-Corasick in Python
  Aho-Corasick/Aho-Corasick.py
Labels: GSSoC20, easy

#2969 Shell Sort In Ruby
  Shell_Sort/Shell_Sort.rb
Labels: GSSoC20, easy

#2964 Tower_Of_Honoi.ts
  Tower_Of_Hanoi/Tower_Of_Hanoi.ts
Labels: GSSoC20, easy

#2967 Extended euclidean
  Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.js
Labels: GSSoC20, beginner

#2970 Cycle Sort In Ruby
  Cycle_Sort/Cycle_Sort.rb
Labels: GSSoC20, easy

#2989 Add Extended Euclidean Algorithm in TypeScript
  Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.ts
Labels: GSSoC20, beginner

#2966 Euclidean Algo added
  Euclidean_Algorithm/Euclidean_Algorithm.js
Labels: GSSoC20, beginner

#2941 Binary Search in TypeScript
  Binary_Search/Binary search.ts
Labels: GSSoC20, beginner

#2919 Added circle_sort.php
  Circle_Sort/Circle_Sort.php
Labels: GSSoC20, easy

#2968 Adding PHP Implementation for Boyer Moore Algo. (Issue #2480)
  Boyer_Moore_Algorithm/Boyer_Moore.php
Labels: GSSoC20, easy

#2904 Sieve Of Eratosthenes #2174
  Sieve_Of_Eratosthenes/Sieve_Of_Eratosthenes.php
Labels: GSSoC20, easy

#2980 Depth first search in Kotlin
  Depth_First_Search/Depth_First_Search.kt
Labels: GSSoC20, easy

#2994 Kosaraju Algorithm Implemenation in Kotlin
  Kosaraju_Algorithm/Kosaraju_Algorithm.kt
Labels: GSSoC20, medium

#2886 Comb Sort in Kotlin
  Comb_Sort/Comb_Sort.kt
Labels: GSSoC20, easy

#2995 Cycle Sort in Go
  Cycle_Sort/Cycle_Sort.go
Labels: GSSoC20, easy

#2984 Pigeonhole sort in Go
  Pigeonhole_Sort/Pigeonhole_Sort.go
Labels: GSSoC20, easy

#2828 KMP in C
  Knuth_Morris_Pratt_Algorithm/KMP.c
Labels: GSSoC20, easy

#2910 Added Karatsuba_Algorithm.php
  Karatsuba_Algorithm/Karatsuba_Algorithm.php
Labels: GSSoC20, medium

#2983 Insertion sort in Rust
  Insertion_Sort/Insertion_Sort.rs
Labels: GSSoC20, easy

#3025 Added Ternary_Search.php
  Ternary_Search/Ternary_Search.php
Labels: GSSoC20, easy

#3004 Linear search #2179
  Linear_Search/Linear_Search.ts
Labels: GSSoC20, beginner

#3038 Create Rabin_karp.js (Fixes #2161 )
  Rabin_Karp/Rabin_karp.js
Labels: GSSoC20, easy

#3040 Rabin Karp implemented in Dart - #2161 resolved
  Rabin_Karp/Rabin_Karp.dart
Labels: GSSoC20, easy

#3041 Cycle sort implemented in Dart - #2146 resolved
  Cycle_Sort/Cycle_Sort.dart
Labels: GSSoC20, easy

#3044 Cocktail Sort In Ruby
  Cocktail_Sort/Cocktail_Sort.rb
Labels: GSSoC20, easy

#3045 Sleep Sort in Go
  Sleep_Sort/Sleep_Sort.go
Labels: GSSoC20, easy

#3034 Implementation of preorder traversal in typescript
  Tree_Preorder_Traversal/Tree_Preorder_Traversal.ts
Labels: GSSoC20, easy

#3048 Selection_Sort in dart issue #2154
  Selection_Sort/Selection_Sort.dart
Labels: GSSoC20, easy

#3010 Add Sieve Of Eratosthenes in TypeScript
  Sieve_Of_Eratosthenes/Sieve_Of_Eratosthenes.ts
Labels: GSSoC20, easy

#2935 Longest_Increasing_Subsequence
  Longest_Increasing_Subsequence/Longest_Increasing_Subsequence.kt
Labels: GSSoC20, easy

#3050 Radix sort implemented in Dart - #2152 resolved
  Radix_Sort/Radix_Sort.dart
Labels: GSSoC20, easy

#3013 Binary Insertion sort in dart
  Binary_Insertion_Sort/Binary_Insertion_Sort.dart.txt
Labels: GSSoC20, easy

#2990 Extended Algorithm README.md
  Python implementation for the Rabin Karp algorithm
Labels: GSSoC20, beginner

#2976 Created Pancake Sort in php
  Pancake_Sort/Pancake_Sort.php
Labels: GSSoC20, easy

#3055 Quick sort in Rust
  Quick_Sort/Quick_Sort.rs
Labels: GSSoC20, easy

#3049 Pancake sort implemented in Dart - #2151 resolved
  Pancake_Sort/Pancake_Sort.dart
Labels: GSSoC20, easy

#2921 Added Ternary_Search.rb
  Ternary_Search/Ternary_Search.rb
Labels: GSSoC20, beginner

#2344 Create README.md
  Floyd_Warshall_Algorithm/README.md
Labels: GSSoC20, easy

#3056 Cocktail sort implemented in Dart - #2144 resolved
  Cocktail_Sort/Cocktail_Sort.dart
Labels: GSSoC20, easy

#2805 Created Insertion_Sort.php
  Insertion_Sort.php
Labels: GSSoC20, easy
